// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmG2MoV54zDMRkgeYvjIoBxwjcfdVBLK0',
    appId: '1:139396063931:web:2d395272a19f6f8c9fff9e',
    messagingSenderId: '139396063931',
    projectId: 'lucky-card-42fae',
    authDomain: 'lucky-card-42fae.firebaseapp.com',
    storageBucket: 'lucky-card-42fae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAF7Z4CAssYVUBiDk41rLAsFfRqrBrdkc',
    appId: '1:139396063931:android:17d2384467209b689fff9e',
    messagingSenderId: '139396063931',
    projectId: 'lucky-card-42fae',
    storageBucket: 'lucky-card-42fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdJUJKDKMA2xqREBA0nTFDEN52bcbjyHo',
    appId: '1:139396063931:ios:231e592e6735f6979fff9e',
    messagingSenderId: '139396063931',
    projectId: 'lucky-card-42fae',
    storageBucket: 'lucky-card-42fae.appspot.com',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdJUJKDKMA2xqREBA0nTFDEN52bcbjyHo',
    appId: '1:139396063931:ios:f5f35ae5a7cf75a19fff9e',
    messagingSenderId: '139396063931',
    projectId: 'lucky-card-42fae',
    storageBucket: 'lucky-card-42fae.appspot.com',
    iosBundleId: 'com.example.card.RunnerTests',
  );
}
